export enum RelationType {
  Father = 'Father',
  Mother = 'Mother',
  Brother = 'Brother',
  Sister = 'Sister',
  Son = 'Son',
  Daughter = 'Daughter',
  Husband = 'Husband',
  Wife = 'Wife',
  Grandfather = 'Grandfather',
  Grandmother = 'Grandmother',
  Uncle = 'Uncle',
  Aunt = 'Aunt',
  Cousin = 'Cousin',
  Nephew = 'Nephew',
  Niece = 'Niece',
  Friend = 'Friend',
  Other = 'Other',
}